export const DS = {
    page1: "To Lucas,\n\n First and foremost, I want to say I'm sorry. I realise making this is quite selfish of me. This gives me closure in exchange for stirring up old feelings for you. I appreciate you reading even this far. I'd understand why if you didn't read any further. I want to emphasize that I don't expect anything from you. You don't need to reply if you don't want too.",

    page2: "I guess the purpose of this is to say thank you. In my ideal world you'd read all of this and it would change how you feel about me but at the end of the day, I know you, and I know that it isn't that easy to change your mind. However, with that said, I still have all these feelings and I want to do something with them, so I hope you can read this and at the very least feel like hot stuff. Being with you is like having the stereo turned all the way up with the windows down and the sun shining. In that same sense, loosing you is like driving out of range of the radio. So I guess I wanted to make this while the music's still loud because I'd regret it if you never knew how much you mean to me in this moment.",

    page3: "As time passes and my feelings erode I can't help but mourn them. In the absence of you I expected these feelings to spoil or sour, but instead they only got sweeter. I thought I would just miss the feeling of having someone there, someone next to me, but honestly, it's been okay. I know that objectively, I don't need you in my life. I'll be okay without you, just as before I met you. I've found a lot of comfort in that sentiment. But its frustrating because now that I've known you, every time I remember you're gone I can't help but feel loss. As my life slowly reverts back to my baseline, I miss the way you came to shape my day to day. While I might not need you, that definitely doesn't change how much I still want to be with you.",

    page4: "You once said to me that I'll find someone else. That this isn't the end of the road for me. I honestly got a little mad when you said that because I felt like you don't even realise how much you mean to me. There's all the obviously positive things: you're so incredibly sweet, and kind, and patient, and smart, and driven, and emotionally intelligent, and passionate, and protective, and you're very very pretty. I love the way you always make sure everyone's included in a conversation, and how you're outspoken in your beliefs and opinions, and how strong your sense of self is and how you really took the time to get to know me. I feel like these were the things that made me so initially attracted to you.",

    page5: "But even with all these positive things, you still have your vices. You're stubborn, and competitive, you have an ego and your favourite form of banter is literally just rage-baiting. It's so contradictory because sometimes these things can piss me off, but they're also the things that made me really fall for you. You can really challenge my perception of the world, and drive me out of my comfort zone. You make me question my own reasoning, you push me to be better (especially at clash royale), and you compel me to assert myself for the sake of myself, even if it makes others uncomfortable. You may view me as 'high value', but to me, even the value in your faults is immeasurable.",

    page6: "Then there's all the little things. Like how you punch your palm for dramatic effect when you talk about some grand masterplan of yours, how you cover your mouth with your thumb when your thinking really hard, and how funny you look when your reading something on your phone because its so small compared to the rest of you so you have to hunch over and look with deep intent. I miss the warmth of your hand and the breadth of your skin and the texture of your hair through my fingers. All these little things hold space in my head like old photos on a mantle that I cherish too much to replace. And as pictures fade and dust collects on all the memories, I'll resent you a little for leaving me with a Lucas-shaped space.",

    page8:"I wish I took more photos and I wish I told you exactly how I felt when I felt it. Every single time I called you silly, I hope you know that what I was really trying to say is that I love spending time with you and I hate that your moving and I feel so stupid for letting myself get so attached and your silly for making me feel this way. I don't really understand why it has to end here. I don't understand why you don't even want to try. To me, a 1.5hr flight isn't even that far away anyways. I still have so much more I want to share with you and I guess I'm angry because we didn't get to do all the things we said we'd do. Even if there is distance I'd still rather be with you than not.",

    page7: " I'm frustrated and embarrassed because I feel like this meant a whole lot more to me but I guess I also do find comfort in the fact that this is probably harder for me than it is for you. I still haven't fully accepted that I'm not going to go into the new year with you and I'm a little bit scared to because then I have no excuses left for why I don't just move on. Maybe it's just because everything feels like it's out of my control, but I feel such a strong lack of closure and resolve and I can't help but hope that this feeling means this isn't over yet. However, I do recognise that's unfair and unrealistic so I hope that by putting all of this out on the table, I get the closure I'm looking for without asking anything from you.",
    
    page9:"Nevertheless, even if I don't understand, even if I'm scared, and even if I'm angry, I still trust you. If you really think that there's nothing to be gained, and if you're really sure that this is when to call it quits, then all I can really say is thank you for making me feel so seen.\n\nAll the best, \nIrene "

};